{{- if .Values.internal.ciliumNetworkPolicy.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-network-policies
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.clusterDescription }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: network-policies
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: network-policies
      # used by renovate
      # repo: giantswarm/network-policies-app
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-cluster
  dependsOn:
    - name: {{ include "resource.default.name" $ }}-cilium
      namespace: {{ $.Release.Namespace }}
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: {{ ((.Values.helmReleases).coredns).interval | default "10m" }}
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/giantswarm/network-policies-app/blob/main/helm/network-policies-app/values.yaml
  values:
    allowEgressToDNS:
      enabled: true
    {{- if $.Values.global.connectivity.proxy.enabled }}
    # We collect the proxy variables from the cluster-values secret to feed them to the netpol helmRelease to create the CNP for proxy access.
    {{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-cluster-values" (include "resource.default.name" .)) }}
    {{- $secret = $secret.data.values | b64dec | fromYaml }}
    allowEgressToProxy:
      enabled: true
      httpProxy: {{ $secret.http_proxy }}
      httpsProxy: {{ $secret.https_proxy }}
    {{- end }}
{{- end }}