apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-cilium
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: {{ .Values.global.metadata.description | quote }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cilium
      # used by renovate
      # repo: giantswarm/cilium-app
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 10m
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/values.yaml
  values:
    ipam:
      mode: kubernetes
    k8sServiceHost: api.{{ include "resource.default.name" $ }}.{{ .Values.global.connectivity.baseDomain }}
    k8sServicePort: "6443"
    kubeProxyReplacement: 'true'
    hubble:
      relay:
        enabled: true
        tolerations:
          - key: "node-role.kubernetes.io/master"
            effect: "NoSchedule"
            operator: "Exists"
          - key: "node-role.kubernetes.io/control-plane"
            effect: "NoSchedule"
            operator: "Exists"
          - key: "node.cloudprovider.kubernetes.io/uninitialized"
            effect: "NoSchedule"
            operator: "Equal"
            value: "true"
      ui:
        tolerations:
          - key: "node-role.kubernetes.io/master"
            effect: "NoSchedule"
            operator: "Exists"
          - key: "node-role.kubernetes.io/control-plane"
            effect: "NoSchedule"
            operator: "Exists"
          - key: "node.cloudprovider.kubernetes.io/uninitialized"
            effect: "NoSchedule"
            operator: "Equal"
            value: "true"
    global:
      podSecurityStandards:
        enforced: {{ .Values.global.podSecurityStandards.enforced }}
