apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-cilium
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.clusterDescription }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cilium
      version: 0.6.1
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 10m
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/values.yaml
  values:
    ipam:
      mode: kubernetes
    {{- if eq .Values.cilium.k8sServiceHost "default" }}
    k8sServiceHost: api.{{ include "resource.default.name" $ }}.{{ .Values.baseDomain }}
    {{- else }}
    k8sServiceHost: {{ .Values.cilium.k8sServiceHost | quote }}
    {{- end }}
    k8sServicePort: {{ .Values.cilium.k8sServicePort }}
    kubeProxyReplacement: strict
    hubble:
      relay:
        enabled: true
    defaultPolicies:
      enabled: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
