apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-cloud-provider-cloud-director
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.clusterDescription }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    giantswarm.io/service-priority: {{ .Values.metadata.servicePriority | quote }}
    {{- include "labels.common" . | nindent 4 }}
    {{- if .Values.metadata.labels }}
    {{- range $key, $val := .Values.metadata.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
spec:
  suspend: true # It will be unsuspended by the post-install/post-upgrade hook in update-values-hook-job.yaml.
  releaseName: cloud-provider-cloud-director
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cloud-provider-cloud-director
      version: 0.2.7
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 10m
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/giantswarm/cloud-provider-cloud-director-app/blob/main/helm/cloud-provider-cloud-director/values.yaml
  valuesFrom:
    - kind: Secret
      name: {{ .Values.userContext.secretRef.secretName | quote }}
      valuesKey: "refreshToken"
      targetPath: "global.basicAuthSecret.refreshToken"
  values:
    global:
      basicAuthSecret:
        create: true
      vcdConfig:
        clusterid: "" # It will be set by the post-install/post-upgrade hook in post-install-rdeid-job.yaml.
        org: {{ .Values.providerSpecific.org | quote }}
        ovdc: {{ .Values.providerSpecific.ovdc | quote }}
        ovdcNetwork: {{ .Values.providerSpecific.ovdcNetwork | quote }}
        site: {{ .Values.providerSpecific.site | quote }}
        vAppName: {{ include "resource.default.name" $  | quote }}
        vipSubnet: {{ .Values.connectivity.network.loadBalancers.vipSubnet }}
        enableVirtualServiceSharedIP: {{ .Values.cloudProvider.enableVirtualServiceSharedIP }}
        oneArm:
          enabled: {{ .Values.cloudProvider.oneArm.enabled }}
