apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.clusterDescription }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    giantswarm.io/service-priority: "{{ .Values.servicePriority }}"
    {{- include "labels.common" . | nindent 4 }}
    {{- range $key, $val := .Values.clusterLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      {{- range .Values.connectivity.network.pods.cidrBlocks }}
      - {{ . }}
      {{- end }}
    services:
      cidrBlocks:
      {{- range .Values.connectivity.network.services.cidrBlocks }}
      - {{ . }}
      {{- end }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ include "resource.default.name" $ }}
    namespace: {{ .Release.Namespace }}
  infrastructureRef:
    apiVersion: {{ include "infrastructureApiVersion" . }}
    kind: VCDCluster
    name: {{ include "resource.default.name" $ }}
    namespace: {{ .Release.Namespace }}
