apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      {{- range .Values.cluster.network.podsCidrBlocks }}
      - {{ . }}
      {{- end }}
    serviceDomain: {{ .Values.cluster.serviceDomain }}
    services:
      cidrBlocks:
      {{- range .Values.cluster.network.servicesCidrBlocks }}
      - {{ . }}
      {{- end }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ include "resource.default.name" $ }}
    namespace: {{ .Release.Namespace }}
  infrastructureRef:
    apiVersion: {{ include "infrastructureApiVersion" . }}
    kind: VCDCluster
    name: {{ include "resource.default.name" $ }}
    namespace: {{ .Release.Namespace }}
