apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-coredns
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.clusterDescription }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: coredns
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: coredns-app
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default
  dependsOn:
    name: {{ include "resource.default.name" $ }}-cilium
    namespace: {{ $.Release.Namespace }}
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 10m
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/giantswarm/coredns-app/blob/main/helm/coredns-app/values.yaml
  values:
    cluster:
      calico:
        CIDR: {{ index .Values.connectivity.network.pods.cidrBlocks 0 | quote }}
      kubernetes:
        API:
          clusterIPRange: {{ index .Values.connectivity.network.services.cidrBlocks 0 | quote }}
        DNS:
          IP: {{ include "clusterDNS" $ | quote }}
