apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: {{ include "resource.default.name" $ }}-default
  namespace: {{ $.Release.Namespace }}
spec:
  interval: 10m
  url: https://giantswarm.github.io/default-catalog
