{{- range $name, $value := .Values.nodePools }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ include "resource.default.name" $ }}-{{ $name }}-{{- include "kubeAdmConfigTemplateRevision" (merge (dict "pool" $value) $) }}
spec:
  template:
    spec:
      {{- include "kubeAdmConfigTemplateSpec" (merge (dict "pool" (set $value "name" $name)) $) | nindent 6 -}}
{{- end }}
