apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - "api.{{ include "resource.default.name" $ }}.{{ .Values.baseDomain }}"
        {{- if .Values.controlPlane.certSANs }}
        {{- range .Values.controlPlane.certSANs}}
        - {{ . }}
        {{- end }}
        {{- end }}
        extraArgs:
          audit-log-maxage: "30"
          audit-log-maxbackup: "30"
          audit-log-maxsize: "100"
          audit-log-path: /var/log/apiserver/audit.log
          audit-policy-file: /etc/kubernetes/policies/audit-policy.yaml
          cloud-provider: external
          {{- if .Values.internal.apiServer.enableAdmissionPlugins }}
          enable-admission-plugins: {{ .Values.internal.apiServer.enableAdmissionPlugins | join "," | quote }}
          {{- end }}
          encryption-provider-config: /etc/kubernetes/encryption/config.yaml
          {{- if .Values.internal.apiServer.featureGates }}
          feature-gates: {{ range $index, $element := .Values.internal.apiServer.featureGates -}}
            {{ if $index }},{{ end }}{{ $element.name }}={{ $element.enabled }}
          {{- end }}
          {{- end }}
          kubelet-preferred-address-types: "InternalIP"
          logtostderr: "true"
          {{- if .Values.controlPlane.oidc.issuerUrl }}
          {{- with .Values.controlPlane.oidc }}
          oidc-issuer-url: {{ .issuerUrl }}
          oidc-client-id: {{ .clientId }}
          oidc-username-claim: {{ .usernameClaim }}
          oidc-groups-claim: {{ .groupsClaim }}
          {{- if .usernamePrefix }}
          oidc-username-prefix: {{ .usernamePrefix | quote }}
          {{- end }}
          {{- if .groupsPrefix }}
          oidc-groups-prefix: {{ .groupsPrefix | quote }}
          {{- end }}
          {{- if .caFile }}
          oidc-ca-file: {{ .caFile }}
          {{- end }}
          {{- end }}
          {{- end }}
          profiling: "false"
          requestheader-allowed-names: "front-proxy-client"
          runtime-config: "api/all=true"
          tls-cipher-suites: "TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_GCM_SHA384"
        extraVolumes:
          - name: auditlog
            hostPath: /var/log/apiserver
            mountPath: /var/log/apiserver
            pathType: DirectoryOrCreate
          - name: policies
            hostPath: /etc/kubernetes/policies
            mountPath: /etc/kubernetes/policies
            pathType: DirectoryOrCreate
          - name: encryption
            hostPath: /etc/kubernetes/encryption
            mountPath: /etc/kubernetes/encryption
            readOnly: false
            pathType: DirectoryOrCreate
      controllerManager:
        extraArgs:
          authorization-always-allow-paths: "/healthz,/readyz,/livez,/metrics"
          bind-address: "0.0.0.0"
          cloud-provider: external
          enable-hostpath-provisioner: "true"          
          terminated-pod-gc-threshold: "125"
          {{- if .Values.internal.controllerManager.featureGates }}
          feature-gates: {{ range $index, $element := .Values.internal.controllerManager.featureGates -}}
            {{ if $index }},{{ end }}{{ $element.name }}={{ $element.enabled }}
          {{- end }}
          {{- end }}
          logtostderr: "true"
          profiling: "false"
      scheduler:
        extraArgs:
          authorization-always-allow-paths: "/healthz,/readyz,/livez,/metrics"
          bind-address: "0.0.0.0"
      dns:
        imageRepository: {{ .Values.controlPlane.dns.imageRepository }}
        imageTag: {{ .Values.controlPlane.dns.imageTag }}
      etcd:
        local:
          extraArgs:
            listen-metrics-urls: "http://0.0.0.0:2381"
          imageRepository: {{ .Values.controlPlane.etcd.imageRepository }}
          imageTag: {{ .Values.controlPlane.etcd.imageTag }}
      imageRepository: {{ .Values.controlPlane.image.repository }}
    {{- include "sshUsers" . | nindent 4 }}
    initConfiguration:
      # TODO we need cluster-api-app@1.8.0 to be able to use skipPhases
      # Right now we do a hackery to workaround this limitation. To revert
      # this:
      #     - remove files/var/run/kubeadm/update-kubeadm-yaml-skip-phases.sh
      #       from the chart directory
      #     - remove files/var/run/kubeadm/update-kubeadm-yaml-skip-phases.sh
      #       references in _kubeadm.tpl
      #     - remove _kubeadm.tpl file from the chart directory
      #     - uncomment lines below
      #skipPhases:
      #  - addon/coredns
      #  - addon/kube-proxy
      patches:
        directory: "/tmp/kubeadm/patches"
      nodeRegistration:
        criSocket: /run/containerd/containerd.sock
        {{- include "taints" .Values.controlPlane.customNodeTaints | nindent 8 }}
        kubeletExtraArgs:
          {{- include "kubeletExtraArgs" . | nindent 10}}
    joinConfiguration:
      patches:
        directory: "/tmp/kubeadm/patches"
      nodeRegistration:
        criSocket: /run/containerd/containerd.sock
        {{- include "taints" .Values.controlPlane.customNodeTaints | nindent 8 }}
        kubeletExtraArgs:
          {{- include "kubeletExtraArgs" . | nindent 10}}
          {{- with .Values.controlPlane.customNodeLabels -}}
          node-labels: "{{- join "," . }}"
          {{- end }}
    files:
      {{- include "auditLogFiles" . | nindent 6 }}
      {{- include "sshFiles" . | nindent 6 }}
      {{- include "ntpFiles" . | nindent 6 }}
      {{- if $.Values.internal.teleport.enabled }}
      {{- include "teleportFiles" . | nindent 6 }}
      {{- end }}
      {{- if $.Values.connectivity.proxy.enabled }}
      {{- include "containerdProxyConfig" . | nindent 6 }}
      {{- include "teleportProxyConfig" . | nindent 6 }}
      {{- end }}
      {{- include "kubeadmFiles" . | nindent 6 }}
      {{- include "containerdConfig" . | nindent 6 }}
      {{- range $kubeadmPatch, $_ :=  .Files.Glob  "files/etc/patches/**" }}
      - path: {{ (printf "/tmp/kubeadm/patches/%s" (base $kubeadmPatch)) }}
        content: |-
          {{- $.Files.Get $kubeadmPatch | nindent 10 }}
      {{- end }}
      - path: /etc/kubernetes/encryption/config.yaml
        permissions: "0600"
        contentFrom:
          secret:
            name: {{ include "resource.default.name" $ }}-encryption-provider-config
            key: encryption
      {{- if $.Values.connectivity.network.staticRoutes }}
      {{- include "staticRoutes" . | nindent 6}}
      {{- end }}
    preKubeadmCommands:
      - bash /tmp/kubeadm/patches/kube-apiserver-patch.sh {{ .Values.controlPlane.resourceRatio }}
      - bash /run/kubeadm/gs-update-kubeadm-yaml-skip-phases.sh
      - /bin/test ! -d /var/lib/kubelet && (/bin/mkdir -p /var/lib/kubelet && /bin/chmod 0750 /var/lib/kubelet)
      {{- if $.Values.connectivity.proxy.enabled }}
      - systemctl daemon-reload
      - systemctl restart containerd
      - systemctl restart teleport
      {{- end }}
      {{- if $.Values.internal.teleport.enabled }}
      - systemctl daemon-reload
      - systemctl enable --now teleport.service
      {{- end }}
      {{- if $.Values.connectivity.network.staticRoutes }}
      - systemctl daemon-reload
      - systemctl enable --now static-routes.service
      {{- end }}
      {{- include "hostEntries" . | nindent 6}}
    postKubeadmCommands:  
      {{- include "sshPostKubeadmCommands" . | nindent 6 }}
      {{- include "ntpPostKubeadmCommands" . | nindent 6 }}
  machineTemplate:
    metadata:
      labels: {{- include "labels.common" . | nindent 8 }}
    infrastructureRef:
      apiVersion: {{ include "infrastructureApiVersion" . }}
      kind: VCDMachineTemplate
      name: {{ include "resource.default.name" . }}-control-plane-{{ include "mtRevisionByControlPlane" $ }}
      namespace: {{ .Release.Namespace }}
  replicas: {{ .Values.controlPlane.replicas }}
  version: {{ .Values.internal.kubernetesVersion }}
