apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ include "resource.default.name" $ }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
      {{- with .Values.kubeadm }}
      dns:
        imageRepository: {{ .dns.image }}
        imageTag: {{ .dns.tag }}
      etcd:
        local:
          imageRepository: {{ .etcd.image }}
          imageTag: {{ .etcd.tag }}
      imageRepository: {{ .imageRepository }}
    {{- end }}
    {{- if .users }}
    {{- range .users }}
    users:
    - name: {{ .name }}
      sshAuthorizedKeys: 
      {{- range .authorizedKeys }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- end }}
    initConfiguration:
      nodeRegistration:
        criSocket: /run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
          cloud-provider: external
    joinConfiguration:
      nodeRegistration:
        criSocket: /run/containerd/containerd.sock
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
          cloud-provider: external
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: VCDMachineTemplate
      name: {{ include "resource.default.name" $ }}-control-plane
      namespace: {{ .Release.Namespace }}
  replicas: {{ .Values.controlPlane.replicas }}
  version: {{ .Values.cluster.kubernetesVersion }}