{{- range $nodePoolName, $value := include "createMapOfWorkerPoolSpecs" . | fromYaml }}
{{- $c := (merge (dict "currentPool"  $value) $.Values) }}
{{/* we deepcopy the $value variable inside the loop because it is mutated when it is passed to
kubeadmConfigTemplateRevision which then affects later functions which also rely on $values.
$valuesDeepCopied should only be used with the call to kubeadmConfigTemplateRevision */}}
{{- $valueDeepCopied := (deepCopy $value) -}}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ include "resource.default.name" $ }}-{{ $nodePoolName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    {{- include "preventDeletionLabel" $ | nindent 4 }}
spec:
  clusterName: {{ include "resource.default.name" $ }}
  replicas: {{ $value.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        {{- include "labels.selector" $ | nindent 8 }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "resource.default.name" $ }}-{{ $nodePoolName }}-{{ include "kubeadmConfigTemplateRevision" (merge (dict "pool" (set $valueDeepCopied "name" $nodePoolName)) $) }}
          namespace: {{ $.Release.Namespace }}
      clusterName: {{ include "resource.default.name" $ }}
      infrastructureRef:
        apiVersion: {{ include "infrastructureApiVersion" . }}
        kind: VCDMachineTemplate
        name: {{ include "resource.default.name" $ }}-{{ $nodePoolName }}-{{ include "mtRevision" $c }}
        namespace: {{ $.Release.Namespace }}
      version: {{ $.Values.internal.kubernetesVersion }}
{{- end }}
