{{- range $name, $value := .Values.nodePools }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ include "resource.default.name" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    {{- include "preventDeletionLabel" $ | nindent 4 -}}
spec:
  clusterName: {{ include "resource.default.name" $ }}
  replicas: {{ $value.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        {{- include "labels.selector" $ | nindent 8 }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "resource.default.name" $ }}-{{ $name }}-{{- include "kubeadmConfigTemplateRevision" (merge (dict "pool" (set $value "name" $name)) $) }}
          namespace: {{ $.Release.Namespace }}
      clusterName: {{ include "resource.default.name" $ }}
      infrastructureRef:
        apiVersion: {{ include "infrastructureApiVersion" . }}
        kind: VCDMachineTemplate
        name: {{ include "resource.default.name" $ }}-{{ $value.class }}-{{ include "mtRevisionByClass" (merge (dict "currentValues" $.Values) $value) }}
        namespace: {{ $.Release.Namespace }}
      version: {{ $.Values.internal.kubernetesVersion }}
{{- end }}
