apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineHealthCheck
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  clusterName: {{ include "resource.default.name" $ }}
  selector:
    matchExpressions:
    - key: cluster.x-k8s.io/cluster-name
      operator: In
      values:
      - {{ include "resource.default.name" $ }}
    - key: cluster.x-k8s.io/control-plane
      operator: DoesNotExist
  checks:
    nodeStartupTimeoutSeconds: 1200
    unhealthyNodeConditions:
    - type: Ready
      status: Unknown
      timeoutSeconds: 600
    - type: Ready
      status: "False"
      timeoutSeconds: 600
  remediation:
    triggerIf:
      unhealthyLessThanOrEqualTo: 40%
