{{- range $name, $value := (merge .Values.providerSpecific.nodeClasses (dict "control-plane" .Values.global.controlPlane)) }}
{{- $c := (merge (dict "currentClass"  $value) $.Values) }}
---
apiVersion: {{ include "infrastructureApiVersion" . }}
kind: VCDMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-{{ $name }}-{{ include "mtRevision" $c }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  template:
    spec:
      {{- include "mtSpec" $c | nindent 6 -}}
{{- end }}
