apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  template:
    spec:
      catalog: {{ .Values.template.catalog }}
      template: {{ .Values.template.controlPlane.template }}
      sizingPolicy: {{ .Values.template.controlPlane.sizingPolicy }}
      placementPolicy: {{ .Values.template.controlPlane.placementPolicy }}
      storageProfile: {{ .Values.template.controlPlane.storageProfile }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-md0
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  template:
    spec:
      catalog: {{ .Values.template.catalog }}
      template: {{ .Values.template.workerNode.template }}
      sizingPolicy: {{ .Values.template.workerNode.sizingPolicy }}
      placementPolicy: {{ .Values.template.workerNode.placementPolicy }}
      storageProfile: {{ .Values.template.workerNode.storageProfile }}