apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  template:
    spec:
      {{- with .Values.template }}
      catalog: {{ .catalog }}
      template: {{ .controlPlane.template }}
      sizingPolicy: {{ .controlPlane.sizingPolicy }}
      placementPolicy: {{ .controlPlane.placementPolicy }}
      storageProfile: {{ .controlPlane.storageProfile }}
      {{- end }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-md0
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  template:
    spec:
      {{- with .Values.template }}
      catalog: {{ .catalog }}
      template: {{ .workerNode.template }}
      sizingPolicy: {{ .workerNode.sizingPolicy }}
      placementPolicy: {{ .workerNode.placementPolicy }}
      storageProfile: {{ .workerNode.storageProfile }}
      {{- end }}