{{- range (append .Values.nodeClasses ((merge (dict "name" "control-plane") .Values.controlPlane))) }}
---
apiVersion: {{ include "infrastructureApiVersion" . }}
kind: VCDMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-{{ .name }}-{{ include "mtRevision" (merge . $) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  template:
    spec:
      catalog: {{ .catalog }}
      template: {{ .template }}
      sizingPolicy: {{ .sizingPolicy }}
      placementPolicy: {{ .placementPolicy }}
      storageProfile: {{ .storageProfile }}
{{- end }}
