apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: VCDMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  template:
    spec:
      catalog: {{ .Values.template.catalog }}
      template: {{ .Values.template.controlPlane.template }}
      computePolicy: {{ .Values.template.controlPlane.computePolicy }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: VCDMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-md0
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  template:
    spec:
      catalog: {{ .Values.template.catalog }}
      template: {{ .Values.template.workerNode.template }}
      computePolicy: {{ .Values.template.workerNode.computePolicy }}