global:
  connectivity:
    network:
      loadBalancers:
        vipSubnet: 10.205.9.254/24
    baseDomain: "test.gigantic.io"
  metadata:
    description: "Testing Cluster"
    name: "test"
    organization: giantswarm
    servicePriority: highest
  controlPlane:
    replicas: 1
    oidc:
      issuerUrl: https://dex.gerbil.test.gigantic.io
      clientId: "dex-k8s-authenticator"
      usernameClaim: "email"
      groupsClaim: "groups"
      caPem: ""
    machineTemplate:
      catalog: giantswarm
      diskSizeGB: 30
      sizingPolicy: m1.medium
  nodePools:
    worker:
      catalog: giantswarm
      replicas: 2
      sizingPolicy: m1.medium
      diskSizeGB: 30
  providerSpecific:
    org: test
    ovdc: test
    ovdcNetwork: test
    site: "https://test.cloud"
    userContext:
      secretRef:
        secretName: vcd-credentials
  release:
    version: 27.0.0
cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
