global:
  connectivity:
    network:
      loadBalancers:
        vipSubnet: 10.205.9.254/24
    baseDomain: "test.gigantic.io"
    containerRegistries:
      gsoci.azurecr.io:
        - endpoint: zot-test-1.golem.gaws.gigantic.io
          credentials:
            username: example
            password: xxxxx
      gsociprivate.azurecr.io:
        - endpoint: zot-test-2.golem.gaws.gigantic.io
          credentials:
            username: example
            password: yyyyy
    localRegistryCache:
      enabled: true
      mirroredRegistries:
        - gsoci.azurecr.io
        - gsociprivate.azurecr.io
  metadata:
    description: "Testing Cluster"
    name: "test"
    organization: giantswarm
    servicePriority: highest
  controlPlane:
    catalog: giantswarm
    replicas: 1
    sizingPolicy: m1.medium
    diskSizeGB: 30
    oidc:
      issuerUrl: https://dex.gerbil.test.gigantic.io
      caFile: ""
      clientId: "dex-k8s-authenticator"
      usernameClaim: "email"
      groupsClaim: "groups"
      usernamePrefix: ""
      groupsPrefix: ""
  nodePools:
    worker:
      catalog: giantswarm
      replicas: 2
      sizingPolicy: m1.medium
      diskSizeGB: 30
  providerSpecific:
    org: test
    ovdc: test
    ovdcNetwork: test
    site: "https://test.cloud"
    userContext:
      secretRef:
        secretName: vcd-credentials

