apiVersion: v1
kind: ConfigMap
metadata:
  name: test-multinic-cluster-user-values
  namespace: org-multi-project
data:
  values: |
    baseDomain: test.gigantic.io
    clusterDescription: test cluster with 2 nics and static route.
    kubernetesVersion: v1.22.9+vmware.1
    organization: multi-project
    metadata:
      servicePriority: highest

    providerSpecific:
      org: giantswarm
      ovdc: vDC 73640
      site: https://vmware.ikoula.com
      ovdcNetwork: capvcd-192.168.52.0

    ##### Not needed in VCD 10.4+
    cloudProvider:
      enableVirtualServiceSharedIP: false
      oneArm:
        enabled: true

    controlPlane:
      catalog: giantswarm
      replicas: 3
      sizingPolicy: m1.medium
      template: ubuntu-2004-kube-v1.22.9

    connectivity:
      network:
        loadBalancers:
          vipSubnet: "178.170.32.1/24"
        extraOvdcNetworks:
        - network-test-2
        staticRoutes:
        - destination: 300.300.300.300/16
          via: 172.32.150.1

    nodeClasses:
      default:
        catalog: giantswarm
        sizingPolicy: m1.medium
        template: ubuntu-2004-kube-v1.22.9

    nodePools:
      worker:
        class: default
        replicas: 2

    userContext:
      secretRef:
        secretName: vcd-credentials
        useSecretRef: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-multinic-da-user-values
  namespace: org-multi-project
data:
  values: |
    clusterName: test-multinic
    managementCluster: guppy
    organization: multi-project
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/managed-by: flux
  name: test-multinic
  namespace: org-multi-project
spec:
  name: cluster-cloud-director
  namespace: org-multi-project
  catalog: cluster-test
  version: 0.8.1-11e4cfd2b778b0bd75bd1724c6b88a13d0fac5fb
  kubeConfig:
    inCluster: true
  userConfig:
    configMap:
      name: test-multinic-cluster-user-values
      namespace: org-multi-project
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/managed-by: flux
  name: test-multinic-default-apps
  namespace: org-multi-project
spec:
  name: default-apps-cloud-director
  namespace: org-multi-project
  catalog: cluster
  version: 0.4.1
  kubeConfig:
    inCluster: true
  userConfig:
    configMap:
      name: test-multinic-da-user-values
      namespace: org-multi-project