apiVersion: v1
kind: ConfigMap
metadata:
  name: test-customname-cluster-user-values
  namespace: org-multi-project
data:
  values: |
    baseDomain: test.gigantic.io
    internal:
      kubernetesVersion: v1.22.9+vmware.1
    metadata:
      description: test cluster configured with custom node names.
      organization: multi-project
      servicePriority: highest

    providerSpecific:
      org: giantswarm
      ovdc: vDC 73640
      site: https://vmware.ikoula.com
      ovdcNetwork: capvcd-192.168.52.0
      nodeClasses:
        default:
          catalog: giantswarm
          sizingPolicy: m1.medium
          template: ubuntu-2004-kube-v1.22.9

      ##### Not needed in VCD 10.4+
      cloudProviderInterface:
        enableVirtualServiceSharedIP: false
        oneArm:
          enabled: true

    controlPlane:
      catalog: giantswarm
      replicas: 3
      sizingPolicy: m1.medium
      template: ubuntu-2004-kube-v1.22.9

    connectivity:
      network:
        loadBalancers:
          vipSubnet: "178.170.32.1/24"

    nodePools:
      worker:
        class: default
        replicas: 2

    userContext:
      secretRef:
        secretName: vcd-credentials
        useSecretRef: true

    vmNamingTemplate: giantswarm-{{.machine.Name | sha256sum | trunc 5}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-customname-da-user-values
  namespace: org-multi-project
data:
  values: |
    clusterName: test-customname
    managementCluster: guppy
    metadata:
      organization: multi-project
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/managed-by: flux
  name: test-customname
  namespace: org-multi-project
spec:
  name: cluster-cloud-director
  namespace: org-multi-project
  catalog: cluster-test
  version: 0.8.1-11e4cfd2b778b0bd75bd1724c6b88a13d0fac5fb
  kubeConfig:
    inCluster: true
  userConfig:
    configMap:
      name: test-customname-cluster-user-values
      namespace: org-multi-project
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/managed-by: flux
  name: test-customname-default-apps
  namespace: org-multi-project
spec:
  name: default-apps-cloud-director
  namespace: org-multi-project
  catalog: cluster
  version: 0.4.1
  kubeConfig:
    inCluster: true
  userConfig:
    configMap:
      name: test-customname-da-user-values
      namespace: org-multi-project