version: 2.1
orbs:
  architect: giantswarm/architect@6.2.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "push-to-cluster-catalog"
          app_catalog: "cluster-catalog"
          app_catalog_test: "cluster-test-catalog"
          chart: "cluster-cloud-director"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
