apiVersion: v1
kind: ConfigMap
metadata:
  name: testing-cluster-user-values
  namespace: org-multi-project
data:
  values: |
    baseDomain: test.gigantic.io
    internal:
      kubernetesVersion: v1.24.10+vmware.1
    metadata:
      description: "Test cluster configured with custom node names"
      organization: multi-project
      servicePriority: highest

    providerSpecific:
      org: giantswarm
      ovdc: "vDC 73640"
      site: https://vmware.ikoula.com
      ovdcNetwork: capvcd-192.168.52.0
      vmNamingTemplate: giantswarm-{{.machine.Name | sha256sum | trunc 5}}
      userContext:
        secretRef:
          secretName: vcd-credentials
          useSecretRef: true
      nodeClasses:
        default:
          catalog: giantswarm
          sizingPolicy: m1.medium
          template: ubuntu-2004-kube-v1.24.10

      ##### Not needed if VCD 10.4+ !
      cloudProviderInterface:
        enableVirtualServiceSharedIP: false
        oneArm:
          enabled: true

    controlPlane:
      catalog: giantswarm
      replicas: 3
      sizingPolicy: m1.medium
      template: ubuntu-2004-kube-v1.24.10
      oidc:
        issuerUrl: https://dex.testing.test.gigantic.io
        caFile: ""
        clientId: "dex-k8s-authenticator"
        usernameClaim: "email"
        groupsClaim: "groups"
        usernamePrefix: ""

    connectivity:
      network:
        loadBalancers:
          vipSubnet: "178.170.32.1/24"
        extraOvdcNetworks:
        - network-test-2
        staticRoutes:
        - destination: 300.300.300.300/16
          via: 172.32.150.1
      proxy:
        enabled: true
      ntp:
        servers:
          - "10.10.10.123"

    nodePools:
      worker:
        class: default
        replicas: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testing-da-user-values
  namespace: org-multi-project
data:
  values: |
    clusterName: testing
    managementCluster: guppy
    metadata:
      organization: multi-project
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/managed-by: flux
  name: testing
  namespace: org-multi-project
spec:
  name: cluster-cloud-director
  namespace: org-multi-project
  catalog: cluster
  version: 0.13.1
  kubeConfig:
    inCluster: true
  userConfig:
    configMap:
      name: testing-cluster-user-values
      namespace: org-multi-project
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/managed-by: flux
  name: testing-default-apps
  namespace: org-multi-project
spec:
  name: default-apps-cloud-director
  namespace: org-multi-project
  catalog: cluster
  version: 0.6.4
  kubeConfig:
    inCluster: true
  userConfig:
    configMap:
      name: testing-da-user-values
      namespace: org-multi-project