apiVersion: v1
kind: ConfigMap
metadata:
  name: testing-cluster-user-values
  namespace: org-multi-project
data:
  values: |
    cluster:
      providerIntegration:
        components:
          systemd:
            timesyncd:
              ntp:
                - 10.10.10.123
    global:
      release: "27.0.0"
      connectivity:
        network:
          loadBalancers:
            vipSubnet: "178.170.32.1/24"
          extraOvdcNetworks:
            - network-test-2
          staticRoutes:
            - destination: 300.300.300.300/16
              via: 172.32.150.1
        proxy:
          enabled: true
          httpProxy: "http://10.205.105.253:3128"
          httpsProxy: "http://10.205.105.253:3128"
          noProxy: "my.domain.com,10.205.105.0/24"
        ntp:
          servers:
            - "10.10.10.123"
        baseDomain: test.gigantic.io
      metadata:
        description: "Test cluster configured with custom node names"
        name: testing # name of the cluster, no spaces allowed
        organization: multi-project
        servicePriority: highest
      controlPlane:
        replicas: 3
        machineTemplate:
          catalog: giantswarm
          sizingPolicy: m1.medium
        oidc:
          issuerUrl: https://dex.testing.test.gigantic.io
          caPem: ""
          clientId: "dex-k8s-authenticator"
          usernameClaim: "email"
          groupsClaim: "groups"
          usernamePrefix: ""
      nodePools:
        worker:
          catalog: giantswarm
          replicas: 2
          sizingPolicy: m1.medium
      providerSpecific:
        org: giantswarm
        ovdc: "vDC 73640"
        site: https://vmware.ikoula.com
        ovdcNetwork: capvcd-192.168.52.0
        vmNamingTemplate: giantswarm-{{.machine.Name | sha256sum | trunc 5}}
        userContext:
          secretRef:
            secretName: vcd-credentials
            useSecretRef: true
        ##### Not needed if VCD 10.4+ !
        cloudProviderInterface:
          enableVirtualServiceSharedIP: false
          oneArm:
            enabled: true
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/managed-by: flux
  name: testing
  namespace: org-multi-project
spec:
  name: cluster-cloud-director
  namespace: org-multi-project
  catalog: cluster
  version: "" # this is provided by the Release
  kubeConfig:
    inCluster: true
  userConfig:
    configMap:
      name: testing-cluster-user-values
      namespace: org-multi-project