version: v3
teleport:
  data_dir: /var/lib/teleport
  join_params:
    token_name: /etc/teleport-join-token
    method: token
  proxy_server: {{ .Values.internal.teleport.proxyAddr }}
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  commands:
  - name: node
    command: [hostname]
    period: 24h0m0s
  - name: arch
    command: [uname, -m]
    period: 24h0m0s
  - name: role
    command: [/opt/teleport-node-role.sh]
    period: 1m0s
  labels:
    ins: {{ .Values.managementCluster }}
    mc: {{ .Values.managementCluster }}
    cluster: {{ include "resource.default.name" $ }}
    baseDomain: {{ .Values.global.connectivity.baseDomain }}
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
