apiVersion: v2
name: cluster-cloud-director
version: 0.4.1
home: https://github.com/giantswarm/cluster-cloud-director
sources:
  - https://github.com/giantswarm/cluster-cloud-director
description: A helm chart for creating Cluster API clusters with the VMware Cloud Director (VCD) infrastructure provider (CAPVCD).
keywords:
  - capvcd
  - vmware
  - cloud
  - director
  - vcd
annotations:
  application.giantswarm.io/team: "rocket"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
restrictions:
  compatibleProviders:
    - cloud-director
dependencies:
  - name: cluster-shared
    version: "0.6.3"
    repository: "https://giantswarm.github.io/cluster-catalog"
