apiServer:
  certSANs: []
  enableAdmissionPlugins: NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,PersistentVolumeClaimResize,DefaultStorageClass,Priority,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
  featureGates: TTLAfterFinished=true
baseDomain: k8s.test
cloudDirector:
  org: ""
  ovdc: ""
  ovdcNetwork: ""
  site: ""
cloudProvider:
  enableVirtualServiceSharedIP: true
  oneArm:
    enabled: false
cluster:
  parentUid: ""
  rdeId: ""
  useAsManagementCluster: false
clusterDescription: ""
clusterLabels: {}
connectivity:
  containerRegistries: {}
controlPlane:
  catalog: ""
  customNodeLabels: []
  dns:
    imageRepository: projects.registry.vmware.com/tkg
    imageTag: v1.7.0_vmware.12
  etcd:
    imageRepository: giantswarm
    imageTag: 3.5.4-0-k8s
  image:
    repository: projects.registry.vmware.com/tkg
  placementPolicy: ""
  resourceRatio: 8
  sizingPolicy: ""
  storageProfile: ""
  template: ""
controllerManager:
  featureGates: ExpandPersistentVolumes=true,TTLAfterFinished=true
kubectlImage:
  name: giantswarm/kubectl
  registry: quay.io
  tag: 1.23.5
kubernetesVersion: ""
network:
  controlPlaneEndpoint:
    host: ""
    port: ""
  extraOvdcNetworks: []
  loadBalancer:
    vipSubnet: ""
  ntp:
    pools: []
    servers: []
  podsCidrBlocks:
    - 100.96.0.0/11
  servicesCidrBlocks:
    - 100.64.0.0/13
  staticRoutes: []
nodeClasses: {}
nodePools: {}
oidc:
  caFile: ""
  clientId: ""
  groupsClaim: ""
  issuerUrl: ""
  usernameClaim: ""
  usernamePrefix: ""
organization: ""
osUsers:
  - name: giantswarm
    sudo: ALL=(ALL) NOPASSWD:ALL
proxy:
  enabled: false
  secretName: ""
servicePriority: highest
sshTrustedUserCAKeys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4cvZ01fLmO9cJbWUj7sfF+NhECgy+Cl0bazSrZX7sU vault-ca@vault.operations.giantswarm.io
userContext:
  secretRef:
    secretName: ""
