apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster01-user-values
  namespace: org-multi-project
data:
  values: |
    clusterName: cluster01
    managementCluster: guppy
    provider: cloud-director

    kubernetesVersion: v1.22.9+vmware.1
    clusterDescription: test cluster
    organization: "multi-project"

    cloudDirector:
      org: vcd_organisation_name
      ovdc: vcd_ovdc_name
      ovdcNetwork: ovdc_network_name
      site: https://vcd-endpoint.acme.com

    controlPlane:
      catalog: giantswarm
      replicas: 3
      sizingPolicy: m1.large
      template: ubuntu-2004-kube-v1.22.9

    network:
      loadBalancer:
        vipSubnet: 10.10.0.0/27

    nodeClasses:
      default:
        catalog: giantswarm
        sizingPolicy: m1.large
        template: ubuntu-2004-kube-v1.22.9

    nodePools:
      worker:
        class: default
        replicas: 2

    userContext:
      secretRef:
        secretName: vcd-credentials
        useSecretRef: true
